### ISSUE TITLE
incomplete subscription-manager example

### ISSUE THREAD

**Issue by jcpunk** [Katello/katello.org#132]
http://katello.org/docs/2.1/user_guide/content_hosts/index.html#how-is-a-content-host-registered

Shouldn't there be a --serverurl= within the subscription manager examples?

**Comment by stbenjam** [comment]
Not necessary, installing the consumer RPM, as shown in the example will configure the /etc/rhsm/rhsm.conf file with the correct info.

```
rpm -Uvh http://$KATELLO_HOSTNAME/pub/katello-ca-consumer-latest.noarch.rpm
```
