### ISSUE TITLE
Travis fails due to html proofer errors

### ISSUE THREAD

**Issue by daviddavis** [Katello/katello.org#216]
**Note: I wasn't sure where to put katello.org issues. If this belongs in redmine, let me know and I can open an issue there.**

Looks like Travis is failing:

https://travis-ci.org/Katello/katello.org/builds/98495743

I think the problem may be that slideshare is blocking Travis or perhaps the HTML-Proofer user agent as I am able to connect to the links in question without any problems.

**Comment by ehelms** [comment]
I think I resolved this issue with #242
